#UFUNC TRIGONOMETRIC
import numpy as np
print("sine value of pi/2")
x = np.sin(np.pi/2)
print(x)
print("\n")
print("sine values for all the values in array")
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x1 = np.sin(arr)
print(x1)
print("\n")
print("Converting degrees into radians")
arr1 = np.array([90, 180, 270, 360])
x2 = np.deg2rad(arr1)
print(x2)
print("\n")
print("Converting radians into degrees")
arr2 = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x3 = np.rad2deg(arr2)
print(x3)
print("\n")
print("Hypotenues")
base = 3
perp = 4
x4 = np.hypot(base, perp)
print(x4)
print("\n")
print("Angles of each values in array")
arr3 = np.array([1, -1, 0.1])
x5 = np.arcsin(arr3)
print(x5)