#NUMPY DATA TYPES
import numpy as np
print("Get the data type of an array object")
arr = np.array([1, 2, 3, 4])
print(arr.dtype)
print("\n")
print("Get the data type of an array containing strings")
arr1 = np.array(['apple', 'banana', 'cherry'])
print(arr1.dtype)
print("\n")
print("Create an array with data type string")
arr2 = np.array([1, 2, 3, 4], dtype='S')
print(arr2)
print(arr2.dtype)
print("\n")
print("Create an array with data type 4 bytes integer")
arr3 = np.array([1, 2, 3, 4], dtype='i4')
print(arr3)
print(arr3.dtype)
print("\n")
print("Change data type from float to integer by using 'i' as parameter value")
arr4 = np.array([1.1, 2.1, 3.1])
newarr = arr4.astype('i')
print(newarr)
print(newarr.dtype)
print("\n")
print("Change data type from integer to boolean")
arr5 = np.array([1, 0, 3])
newarr = arr5.astype(bool)
print(newarr)
print(newarr.dtype)