#UFUNC SET OPERATIONS
import numpy as np
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
print("Create Sets")
x = np.unique(arr)
print(x)
print("\n")
print("Finding Union")
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)
print("\n")
print("Finding Intersection")
newarr1 = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr1)
print("\n")
print("Finding Difference")
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr2 = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr2)
print("\n")
print("Finding Symmetric Difference")
newarr3 = np.setxor1d(set1, set2, assume_unique=True)
print(newarr3)