#USING RAND() AND CHOICE()
from numpy import random
x = random.rand()
print("To generate a random float from 0 to 1")
print(x)
print("\n")
x1 = random.rand(5)
print("To generate an array containing random floats")
print(x1)
print("\n")
x2 = random.rand(3, 5)
print("To generate a 2-D array containing random floats")
print(x2)
print("\n")
x3 = random.choice([3, 5, 7, 9])
print("Generating random number from an array")
print(x3)
print("\n")
x4 = random.choice([3, 5, 7, 9], size=(3, 5))
print("Generating a 2-D array that consists of the values in the array parameter")
print(x4)
