#UFUNC ROUNDING DECIMALS
import numpy as np
arr = np.trunc([-3.1666, 3.6667])
print("Rounding off using trunc()")
print(arr)
print("\n")
print("Rounding off using fix()")
arr = np.fix([-3.1666, 3.6667])
print(arr)
print("\n")
print("Rounding off using around()")
arr = np.around(3.1666, 2)
print(arr)
print("\n")
print("floor() function")
arr = np.floor([-3.1666, 3.6667])
print(arr)
print("\n")
print("ceil() function")
arr = np.ceil([-3.1666, 3.6667])
print(arr)